## 항만 병목 요인과 분석 프레임
항만도 선박이 오래 기다리거나 컨테이너가 늦게 나가게 되면 병목현상이 발생할 수 있다. 항만에서의 병목 현상은 항만 전체가 아니라 어떤 흐름 중 한 단계에 작업이 몰리거나 지연이 있어서 발생할 수 있다.

항만에서 병목을 만드는 요익을 해측,터미널측,육상측 정보 영역으로 나누어 정리하고 공개데이터를 이용하여 병목을 측정하기 위한 선석,대기,체류 분석 프레임을 살펴보겠다.

### 병목 현상
병목(bottle neck)은 여러 단계가 이어진 작업 흐름에서 처리 능력이 가장 작기 때문에 전체 흐름의 속도를 결정할 수 있는 단계를 의미한다.

병목이 아닌 단계를 아무리 개선해도 전체 속도에는 영향이 없다. 병목을 해소한다고 해서 모든 문제가 해소되지는 않는다. 왜냐하면 그 다음으로 느렸던 단계가 새로운 병목이 될 수 있기 때문이다.

그렇기 때문에 병목 분석은 한 번의 진단으로 끝내는 것이 아니라 개선 후에 다시 측정하는 반복과정이 있어야 한다.

### 처리능력과 수요
병목을 측정하고 관리하기 위해서는 병목을 숫자로 살펴볼 수 있어야 한다. 각각의 단계에 대해서 처리능력(capacity), 해당 단계에 들어오는 수요(demand)를 비교해야 한다.

처리능력은 한 단계가 정해진 시간 안에 최대한 처리할 수 있는 양이고 수요는 실제로 그 단계에 도착한 양을 의미한다.

수요가 처리 능력보다 크지 못하면 처리하지 못한 양이 대기열이 되고 그 대기열이 앞 단계까지 거꾸로 밀려 올라가기 때문이다.

이 두 값의 비율을 이용율이라고 일컫는다. 선석의 경우에는 선박으로 사용되고 있던 시간의 비율로 볼 수 있고 이것이 바로 선석 점유율로 볼 수 있다.

- 이용율 = 수요/처리능력 * 100
- 선석점유율 = 선박이 선석에 머문 시간의 총합/ 관측 기간의 전체시간 * 100

## 항만 병목 요인

항만에서 병목현상이 발생할 수 있는 요인이 무엇인가?
- 선석이 부족해서 병목현상이 발생할 수 있다.
- 선석은 충분하지만 장치장이 가득차서 하역이 느려졌다.
- 트럭이 한꺼번에 몰려서 게이트가 막혀서 병목현상이 발생할 수 있다.

- 해측: 선석 부족, 선박 대형화, 도착 불규칙, 도선/예선의 부족, 기상
- 터미널측: 하역 장비 생산성, 장치장 적재율, 작업/인력 교대
- 육상 측: 게이트 처리능력, 트럭 반출입 시간 몰림, 배후 도로/철도 관리상 문제
- 정보/제도: 신고/허가 지연, 기관간 정보 공유 부족, 명절(기간특수성)

## 분석 프레임
분석을 시작하기 이전에 무엇을 어떤 지표로 어떤 데이터로 볼 것인가를 결정해두어야 하는데 이를 분석 프레임(analysis framework)라고 일컫는다.

건강검진시 혈압,혈당,콜레스트롤 수치 등 정해진 항목을 늘 같은 방식으로 측정한다. 분석 프레임도 마찬가지의 개념으로 항목과 측정 방법을 고정해두어야 시기별/부두별 결과를 서로 비교할 수 있기 때문에 미리 정해두는 것을 의미한다.

선박 한 척이 항만에서 겪는 시간을 세 부분(선석, 대기, 체류)으로 나누어 프레임을 결정한다.

- 선석: 시설이 얼마나 사용중인지(계선장소, 시설코드)
- 대기: 선박이 부두에 붙기 전에 얼마나 기다렸나(선박입항신고, 관제정보)
- 체류: 선박이 항목에 머문 시간이 계획적이었나(관제정보, 선박입항신고

예시: 해양수산부- 해양항만물류정보시스템-선박입항신고 + 해양수산부-항만시설제원코드
<선석에 대한 내용 알 수 있음>
해양수산부 - 해양항만물류정보시스템-선박관제정보 <대기 정보에 대해 알 수 있음>

### 지표 계산식
계산식을 미리 만들어두면 "누가 계산해도 같은 결과를 얻을 수 있고 제외 조건을 누락시키는 실수도 줄일 수 있다."

- 예정 체류시간 = (출항예정일시 - 입항일자) / 시간
- 선석 점유율 = 선석에 선박이 한 척 있었더 시간 / 관측기간 전체시 * 100
- 평균 동시 척수(선석에 동시에 있는 배의 갯수)= 선석별 에정 체류시간의 합 / 관측 기간 전체 시간
- 묘박지 입항 비율= 계선장소가 묘박지(수역시설)인 입항건수/전체 입항 건수 * 100
- 실제 체류기간= (출항 일시- 입항일시) / 시간
- 출항지연시간 = 출항 일시 - 출항 예정 일시

### 데이터간 연결성
- 계선장소시설코드를 코드로 하여 연결 - 불일치 존재
- 호출부호, 년도, 항차 연결


# 분석 절차
1. 질문 정하기 : 어느 관점(선석/대기/체류)의 어떤 병목을 볼 것인가
2. 데이터 선택: 어떤 데이터가 필요한가
3. 품질 확인: 선택된 데이터의 품질은 어떠한가
4. 지표 계산: 프레임의 계산식과 제외조건을 적용한 지표를 계산
5. 비교: 선석, 부두, 월별, 선종간 비교
6. 원인 가설: 데이터로 보이는 증상과 보이지 않는 원인을 나누어 정리

병목의 성질
- 병목이 아닌 단계를 개선해도 처리량이 늘거나 하지는 않는다.
- 병목을 해소하면 그 다음으로 느린 단계가 다시 병목이 된다.

수요가 병목의 처리능력보다 크면 처리하지 못하는 양이 매일 누적되는데 이를 적체라고 일컫는다.

## 이용률, 선석 점유율
병목을 찾으려면 단계마다 얼마나 바쁜가를 기준으로 비교해야 한다. 이용률이 사용된다.

항만에서는 선석의 이용률을 선석점유율로 나타내서 계산한다.
- 선석 점유율 = 선박이 선석에 머문 시간의 합 / 관측 기간 전체 시간
- 한달 = (선박 22척이 평균 26시간을 머무름=22*26)/720 = 572/720 * 100 = 79.44%
    다만 평균은 너무 적거나 많으면 가려지기에 개별 선석을 따지는 게 정확함

## 이용률과 대기시간
점유율 80%, 대기 20%(대기행렬계산..

- p(이용률): 0~1 사이로 나타낸 값
- 평균 작업시간: 선박 한척이 선석을 쓰는 평균 시간

'''
평균 대기시간 = p/(1-p) * 평균 작업시간
'''

작업시간이 24시간인 선석에서 이용률이 50%면 평균 대기는 24시간이지만 80%면 96시간 90%면 216시간으로 이용률이 조금 오를 때마다 대기시간이 곱절로 증가하게 된다.

이용률이 1에 가까워지면 분모는 (1-p)에 가까워지기 때문에 대기가 끝없이 커진다.

-- 선석이 하나이고 도착과 작업시간이 모두 무작위

In [26]:
from PIL.Image import EXTENSION


def get_data_file_path(filename):
    BASE_DIR = './data'
    EXTENSION= '.csv'
    return f'{BASE_DIR}/{filename}{EXTENSION}'

In [27]:
TARGET_FILE = '입항신고'
get_data_file_path(TARGET_FILE)

'./data/입항신고.csv'

In [28]:
import pandas as pd
target = get_data_file_path(TARGET_FILE)
cols = [
    '항구명', '호출부호', '년도','항차', '계선장소시설코드', '계선장소명', '선박종류','입항일자','입항목적','출항예정일시'
]

df = pd.read_csv(target, encoding='euc-kr', usecols=cols)

df.shape

(247056, 10)

In [29]:
call = df[df['항구명'] == '부산']
# call.shape

In [30]:
call.duplicated().sum() # 중복되는 항목 확인
# 중복 행 확인 call.duplicated // sum 추가는 갯수

# 중복행 제거
call = call.drop_duplicates().copy()
# -> 참조
# 기본 자료형/참조 자료형(어딘가에 있는 값을 쓰는 것= 데이터가 저장된 메모리의 주소 값을 저장-> a만 복사하는 건 얕은 복사, a랑 b를 다 복사하면 깊은 복사)

In [31]:
call['입항일자'].sort_values()

103946    2004-01-01 00:00:00
99159     2015-09-04 20:35:00
164642    2016-04-06 12:00:00
146898    2016-05-29 18:05:00
113848    2016-08-16 16:15:00
                 ...
246897    2025-07-31 09:05:00
246647    2025-07-31 09:49:00
246732    2025-07-31 11:10:00
246885    2025-07-31 11:30:00
247051    2025-07-31 15:00:00
Name: 입항일자, Length: 54989, dtype: str

In [32]:
call['출항예정일시']

0         2024-05-02 05:00:00
3         2024-05-02 07:00:00
4         2024-05-01 22:00:00
8         2024-05-01 23:00:00
34        2024-05-01 07:00:00
                 ...
247048    2025-07-10 15:50:00
247049    2025-07-11 07:50:00
247050    2025-07-11 11:00:00
247051    2025-07-31 16:00:00
247052    2025-07-31 08:00:00
Name: 출항예정일시, Length: 54989, dtype: str

In [33]:
call['입항']= pd.to_datetime(call['입항일자'], errors='coerce')
call['입항'].isna().sum()
call['입항'].min()

Timestamp('2004-01-01 00:00:00')

In [34]:
planned_year = pd.to_numeric(call['출항예정일시'].str[:4], errors='coerce')
(planned_year > 2030).sum()

np.int64(9)

In [35]:
call.loc[planned_year > 2030, '출항예정일시']

10037     2424-05-20 16:00:00
12547     2424-05-25 18:00:00
83734     2824-09-30 13:00:00
88219     3024-10-11 05:30:00
95705     2204-10-25 04:00:00
112154    2054-11-25 12:00:00
177562    2205-03-24 18:00:00
191884    2525-04-21 18:00:00
194667    2525-04-17 16:10:00
Name: 출항예정일시, dtype: str

In [36]:
call['출항예정']=pd.to_datetime(call['출항예정일시'].where(planned_year <= 2030), errors='coerce')
call

,항구명,호출부호,년도,항차,계선장소시설코드,계선장소명,선박종류,입항일자,입항목적,출항예정일시,입항,출항예정
0,부산,9VFX4,2024,4,MBS05,신선대부두 5선석,풀컨테이너선,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00,2024-05-01 03:00:00,2024-05-02 05:00:00
3,부산,A8UX4,2024,3,MSN06,신항 2부두 3선석,풀컨테이너선,2024-05-01 04:15:00,양적하,2024-05-02 07:00:00,2024-05-01 04:15:00,2024-05-02 07:00:00
4,부산,3FER7,2024,1,MSN02,신항 1부두 2선석,풀컨테이너선,2024-05-01 07:53:00,적하,2024-05-01 22:00:00,2024-05-01 07:53:00,2024-05-01 22:00:00
8,부산,5LGV4,2024,4,MS402,신항 4부두 2선석,풀컨테이너선,2024-04-30 21:40:00,양적하,2024-05-01 23:00:00,2024-04-30 21:40:00,2024-05-01 23:00:00
34,부산,VRNX4,2024,14,MB602,자성대부두 62선석,풀컨테이너선,2024-04-30 12:45:00,양적하,2024-05-01 07:00:00,2024-04-30 12:45:00,2024-05-01 07:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
247048,부산,060333,2025,487,MK202,감천 2부두 2선석,기타선,2025-07-10 12:55:00,기타,2025-07-10 15:50:00,2025-07-10 12:55:00,2025-07-10 15:50:00
247049,부산,060333,2025,488,*WN01,남항 물량장,기타선,2025-07-10 16:25:00,기타,2025-07-11 07:50:00,2025-07-10 16:25:00,2025-07-11 07:50:00
247050,부산,060333,2025,489,MQC01,한진 중공업 안벽,기타선,2025-07-11 08:15:00,기타,2025-07-11 11:00:00,2025-07-11 08:15:00,2025-07-11 11:00:00
247051,부산,BL2167,2025,1,WAN03,남외항 N-3박지,원양 어선,2025-07-31 15:00:00,선용품적재,2025-07-31 16:00:00,2025-07-31 15:00:00,2025-07-31 16:00:00
247052,부산,111002,2025,25,WAE02,E박지 E2 묘지,석유제품 운반선,2025-07-29 09:00:00,양하,2025-07-31 08:00:00,2025-07-29 09:00:00,2025-07-31 08:00:00

In [37]:
# 분석 기간
# 24.05.01-25.07.31
in_period = (call['입항']>= '2024-05-01') &(call['입항']<'2025-08-01')
in_period
# (~in_period) 블린 마스크 /설정한 기간 바깥에 애들을 잡음
# (~in_period).sum()기간 외 애들 갯수

call2 = call[in_period].copy()
len(call2)

53508

In [38]:
TARGET1 = get_data_file_path('항만시설제원코드')
df1 = pd.read_csv(TARGET1, encoding='euc-kr')
facility = df1[df1['항만']=='부산항']

In [39]:
facility

      항만  시설이용구분  시설구분          시설명 선석 구분      코드
0    부산항  계류시설 M  선석 B          1부두  10선석  MB1-00
1    부산항  계류시설 M  선석 B          1부두  11선석  MB1-01
2    부산항  계류시설 M  선석 B          1부두  12선석  MB1-02
3    부산항  계류시설 M  선석 B          1부두  13선석  MB1-03
4    부산항  계류시설 M  선석 B          1부두  14선석  MB1-04
..   ...     ...   ...          ...   ...     ...
300  부산항      기타    기타    공동어시장앞물량장   NaN  *WG-01
301  부산항      기타    기타       남항 물량장   NaN  *WN-01
302  부산항      기타    기타  영도수산진흥원 물량장   NaN  *WY-01
303  부산항      기타    기타         영도조선   NaN  *YD-01
304  부산항      기타    기타  기타 남항 사설조선소   NaN  *YQ-01

[305 rows x 6 columns]

In [40]:
facility.shape

(305, 6)

In [41]:
call['계선장소시설코드'].head(3)

0    MBS05
3    MSN06
4    MSN02
Name: 계선장소시설코드, dtype: str

In [42]:
facility['코드'].head(3)

0    MB1-00
1    MB1-01
2    MB1-02
Name: 코드, dtype: str

In [43]:
facility['조인코드'] = facility['코드'].str.replace('-', '', regex=False)
facility

      항만  시설이용구분  시설구분          시설명 선석 구분      코드   조인코드
0    부산항  계류시설 M  선석 B          1부두  10선석  MB1-00  MB100
1    부산항  계류시설 M  선석 B          1부두  11선석  MB1-01  MB101
2    부산항  계류시설 M  선석 B          1부두  12선석  MB1-02  MB102
3    부산항  계류시설 M  선석 B          1부두  13선석  MB1-03  MB103
4    부산항  계류시설 M  선석 B          1부두  14선석  MB1-04  MB104
..   ...     ...   ...          ...   ...     ...    ...
300  부산항      기타    기타    공동어시장앞물량장   NaN  *WG-01  *WG01
301  부산항      기타    기타       남항 물량장   NaN  *WN-01  *WN01
302  부산항      기타    기타  영도수산진흥원 물량장   NaN  *WY-01  *WY01
303  부산항      기타    기타         영도조선   NaN  *YD-01  *YD01
304  부산항      기타    기타  기타 남항 사설조선소   NaN  *YQ-01  *YQ01

[305 rows x 7 columns]

In [44]:
facility[facility['조인코드'].duplicated(keep=False)]

     항만  시설이용구분  시설구분    시설명 선석 구분      코드   조인코드
74  부산항  계류시설 M  선석 B  감만 부두   2선석  MBR-02  MBR02
75  부산항  계류시설 M  선석 B  감만 부두   2선석  MBR-02  MBR02
77  부산항  계류시설 M  선석 B  감만 부두   4선석  MBR-04  MBR04
78  부산항  계류시설 M  선석 B  감만 부두   5선석  MBR-04  MBR04

In [45]:
facility= facility.drop_duplicates('조인코드')

In [46]:
facility[facility['조인코드'].duplicated(keep=False)]

Empty DataFrame
Columns: [항만, 시설이용구분, 시설구분, 시설명, 선석 구분, 코드, 조인코드]
Index: []

In [47]:
#calls = call.merge(
#    facility['조인코드'],
#    left_on='계선장소시설코드',           # 컬럼 이름 쓰는 것
#    right_on='조인코드',
#    how='left', # inner left right
#)

# calls
# 시리즈 지정

In [48]:
use_cols = ['조인코드', '시설이용구분', '시설구분']
calls = call.merge(
    facility[use_cols],
    left_on='계선장소시설코드',
    right_on='조인코드',
    how='left' # inner, left, right
)

calls

,항구명,호출부호,년도,항차,계선장소시설코드,계선장소명,선박종류,입항일자,입항목적,출항예정일시,입항,출항예정,조인코드,시설이용구분,시설구분
0,부산,9VFX4,2024,4,MBS05,신선대부두 5선석,풀컨테이너선,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00,2024-05-01 03:00:00,2024-05-02 05:00:00,MBS05,계류시설 M,선석 B
1,부산,A8UX4,2024,3,MSN06,신항 2부두 3선석,풀컨테이너선,2024-05-01 04:15:00,양적하,2024-05-02 07:00:00,2024-05-01 04:15:00,2024-05-02 07:00:00,MSN06,계류시설 M,선석 S
2,부산,3FER7,2024,1,MSN02,신항 1부두 2선석,풀컨테이너선,2024-05-01 07:53:00,적하,2024-05-01 22:00:00,2024-05-01 07:53:00,2024-05-01 22:00:00,MSN02,계류시설 M,선석 S
3,부산,5LGV4,2024,4,MS402,신항 4부두 2선석,풀컨테이너선,2024-04-30 21:40:00,양적하,2024-05-01 23:00:00,2024-04-30 21:40:00,2024-05-01 23:00:00,MS402,계류시설 M,선석 S
4,부산,VRNX4,2024,14,MB602,자성대부두 62선석,풀컨테이너선,2024-04-30 12:45:00,양적하,2024-05-01 07:00:00,2024-04-30 12:45:00,2024-05-01 07:00:00,MB602,계류시설 M,선석 B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54984,부산,060333,2025,487,MK202,감천 2부두 2선석,기타선,2025-07-10 12:55:00,기타,2025-07-10 15:50:00,2025-07-10 12:55:00,2025-07-10 15:50:00,MK202,계류시설 M,선석 K
54985,부산,060333,2025,488,*WN01,남항 물량장,기타선,2025-07-10 16:25:00,기타,2025-07-11 07:50:00,2025-07-10 16:25:00,2025-07-11 07:50:00,*WN01,기타,기타
54986,부산,060333,2025,489,MQC01,한진 중공업 안벽,기타선,2025-07-11 08:15:00,기타,2025-07-11 11:00:00,2025-07-11 08:15:00,2025-07-11 11:00:00,MQC01,계류시설 M,안벽 Q
54987,부산,BL2167,2025,1,WAN03,남외항 N-3박지,원양 어선,2025-07-31 15:00:00,선용품적재,2025-07-31 16:00:00,2025-07-31 15:00:00,2025-07-31 16:00:00,WAN03,수역 W,박지 A
54988,부산,111002,2025,25,WAE02,E박지 E2 묘지,석유제품 운반선,2025-07-29 09:00:00,양하,2025-07-31 08:00:00,2025-07-29 09:00:00,2025-07-31 08:00:00,WAE02,수역 W,박지 A

In [49]:
unmatched = calls['시설이용구분'].isna()#.sum()

In [50]:
calls.loc[unmatched, '계선장소명'].value_counts()

계선장소명
신항 7부두 2선석    291
신항 7부두 3선석    251
신항 7부두 1선석    250
북항 내 공사구간      11
2부두 22선석        1
Name: count, dtype: int64

In [51]:
in_new_7 = calls['계선장소시설코드'].str.startswith('MS7')
calls.loc[in_new_7, ['시설이용구분', '시설구분']] = ['계류시설 M', '선석 S']

In [52]:
calls['시설이용구분'].value_counts()

시설이용구분
계류시설 M    39761
수역 W       8713
기타         6503
Name: count, dtype: int64

In [53]:
calls['시설이용구분']

0        계류시설 M
1        계류시설 M
2        계류시설 M
3        계류시설 M
4        계류시설 M
          ...
54984    계류시설 M
54985        기타
54986    계류시설 M
54987      수역 W
54988      수역 W
Name: 시설이용구분, Length: 54989, dtype: str

In [54]:
calls['시설구분'].value_counts()

시설구분
선석 B       12135
소형선부두 W    10958
선석 S        9214
박지 A        8713
기타          6503
선석 K        5061
조선소 Y        957
돌핀 D         623
안벽 Q         580
잔교 F         233
Name: count, dtype: int64